[package]
name = "winrt-bindings"
version = "0.2.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
windows = "0.23"

[build-dependencies]
windows = "0.23"
