[package]
name = "tunet-helper"
version = "0.13.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
authtea = { workspace = true }
async-trait = { workspace = true }
async-stream = "0.3"
futures-core = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
url = "2"
md-5 = "0.10"
sha-1 = "0.10"
hmac = "0.12"
data-encoding = "2"
data-encoding-macro = "0.1"
serde_json = { workspace = true }
select = "0.6"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
mac_address = { workspace = true }
once_cell = { workspace = true }
regex = { version = "1", default-features = false, features = ["std"] }
thiserror = { workspace = true }
enum_dispatch = { workspace = true }
anyhow = { workspace = true }

[target.'cfg(all(target_os = "linux", any(target_arch = "i686", target_arch = "x86_64", target_arch = "arm", target_arch = "aarch64")))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
    "cookies",
    "json",
] }

[target.'cfg(all(target_os = "linux", not(any(target_arch = "i686", target_arch = "x86_64", target_arch = "arm", target_arch = "aarch64"))))'.dependencies]
reqwest = { version = "0.11", features = [
    "native-tls-vendored",
    "cookies",
    "json",
] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
reqwest = { version = "0.11", features = ["cookies", "json"] }
