[package]
name = "tunet-helper"
version = "0.15.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
authtea = { workspace = true }
async-trait = { workspace = true }
async-stream = "0.3"
futures-core = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
reqwest = { version = "0.11", features = ["cookies", "json"] }
url = "2"
md-5 = "0.10"
sha-1 = "0.10"
hmac = "0.12"
data-encoding = "2"
data-encoding-macro = "0.1"
serde_json = { workspace = true }
select = "0.6"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
mac_address = { workspace = true }
once_cell = { workspace = true }
regex = { version = "1", default-features = false, features = ["std"] }
thiserror = { workspace = true }
enum_dispatch = { workspace = true }
