[package]
name = "tunet-helper"
version = "0.16.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
authtea = { workspace = true }
netstatus = { workspace = true }
async-stream = "0.3"
futures-core = { workspace = true }
reqwest = { version = "0.11", default-features = false, features = [
    "cookies",
    "json",
] }
url = "2"
md-5 = "0.10"
sha-1 = "0.10"
hmac = "0.12"
data-encoding = "2"
base64 = { workspace = true }
serde_json = { workspace = true }
select = "0.6"
chrono = { workspace = true }
mac_address2 = { workspace = true }
once_cell = { workspace = true }
regex = { version = "1", default-features = false, features = ["std"] }
thiserror = { workspace = true }
allo-isolate = { version = "0.1", features = ["chrono"], optional = true }

[target.'cfg(target_os = "android")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }

[target.'cfg(not(target_os = "android"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = [
    "native-tls",
] }

[features]
default = []
dart = ["allo-isolate"]
