[workspace]
members = [
    "authtea",
    "netstatus",
    "color-theme",
    "keyring",
    "tunet-helper",
    "tunet-suggest",
    "tunet-settings",
    "tunet-model",
    "tunet-model-native",
    "tunet",
]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
