[workspace]
members = [
    "authtea",
    "tunet-rust",
    "tunet"
]

exclude = [
    "netstatus",
    "keyring",
    "winrt-bindings"
]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
