[workspace]
members = [
    "authtea",
    "tunet-rust",
    "tunet-settings",
    "tunet-model",
    "tunet",
    "tunet-gui",
]

exclude = [
    "netstatus",
    "keyring",
    "winrt-bindings",
]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
