[workspace]
members = [
    "authtea",
    "tunet-rust",
    "tunet",
    "tunet-native"
]

exclude = [
    "netstatus",
    "winrt-bindings",
    "libiw-bindings"
]

[profile.release]
lto = true
