[package]
name = "tunet-rust"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[lib]
path = "src/lib.rs"

[profile.release]
lto = true

[dependencies]
reqwest = "0.9"
rust-crypto = "0.2"
serde_json = "1.0"
rustc-serialize = "0.3"
select = "0.4"
chrono = "0.4"
structopt = {version = "0.3", optional = true}
itertools = {version = "0.8", optional = true}
ansi_term = {version = "0.12", optional = true}
rpassword = {version = "4.0", optional = true}
dirs = {version = "2.0", optional = true}
base64 = {version = "0.11", optional = true}

[features]
build-bin = ["structopt", "itertools", "ansi_term", "rpassword", "dirs", "base64"]

[[bin]]
name = "tunet"
path = "bin/tunet.rs"
required-features = ["build-bin"]
