// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.78.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<Runtime> newStaticMethodRuntime({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_new__static_method__Runtime(port_),
      parseSuccessData: (d) => _wire2api_runtime(d),
      constMeta: kNewStaticMethodRuntimeConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "new__static_method__Runtime",
        argNames: [],
      );

  Stream<UpdateMsgWrap> startMethodRuntime(
      {required Runtime that,
      required RuntimeStartConfig config,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_box_autoadd_runtime_start_config(config);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_start__method__Runtime(port_, arg0, arg1),
      parseSuccessData: _wire2api_update_msg_wrap,
      constMeta: kStartMethodRuntimeConstMeta,
      argValues: [that, config],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStartMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "start__method__Runtime",
        argNames: ["that", "config"],
      );

  Future<NetStatus> currentStatusMethodRuntime(
      {required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_current_status__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api_net_status,
      constMeta: kCurrentStatusMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCurrentStatusMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "current_status__method__Runtime",
        argNames: ["that"],
      );

  Future<(String, String)> loadCredentialMethodRuntime(
      {required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_load_credential__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api___record__String_String,
      constMeta: kLoadCredentialMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kLoadCredentialMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "load_credential__method__Runtime",
        argNames: ["that"],
      );

  Future<void> saveCredentialMethodRuntime(
      {required Runtime that,
      required String u,
      required String p,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_String(u);
    var arg2 = _platform.api2wire_String(p);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_save_credential__method__Runtime(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kSaveCredentialMethodRuntimeConstMeta,
      argValues: [that, u, p],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSaveCredentialMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "save_credential__method__Runtime",
        argNames: ["that", "u", "p"],
      );

  Future<void> queueCredentialMethodRuntime(
      {required Runtime that,
      required String u,
      required String p,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_String(u);
    var arg2 = _platform.api2wire_String(p);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_queue_credential__method__Runtime(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueCredentialMethodRuntimeConstMeta,
      argValues: [that, u, p],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueCredentialMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_credential__method__Runtime",
        argNames: ["that", "u", "p"],
      );

  Future<void> queueLoginMethodRuntime({required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_login__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueLoginMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueLoginMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_login__method__Runtime",
        argNames: ["that"],
      );

  Future<void> queueLogoutMethodRuntime({required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_logout__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueLogoutMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueLogoutMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_logout__method__Runtime",
        argNames: ["that"],
      );

  Future<void> queueFluxMethodRuntime({required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_flux__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueFluxMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueFluxMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_flux__method__Runtime",
        argNames: ["that"],
      );

  Future<void> queueStateMethodRuntime(
      {required Runtime that, NetState? s, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_opt_box_autoadd_net_state(s);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_state__method__Runtime(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueStateMethodRuntimeConstMeta,
      argValues: [that, s],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueStateMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_state__method__Runtime",
        argNames: ["that", "s"],
      );

  Future<void> queueStatusMethodRuntime(
      {required Runtime that, required NetStatus s, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_box_autoadd_net_status(s);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_status__method__Runtime(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueStatusMethodRuntimeConstMeta,
      argValues: [that, s],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueStatusMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_status__method__Runtime",
        argNames: ["that", "s"],
      );

  Future<void> queueDetailsMethodRuntime(
      {required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_details__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueDetailsMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueDetailsMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_details__method__Runtime",
        argNames: ["that"],
      );

  Future<void> queueOnlinesMethodRuntime(
      {required Runtime that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_onlines__method__Runtime(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueOnlinesMethodRuntimeConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueOnlinesMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_onlines__method__Runtime",
        argNames: ["that"],
      );

  Future<void> queueConnectMethodRuntime(
      {required Runtime that, required Ipv4AddrWrap ip, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_box_autoadd_ipv_4_addr_wrap(ip);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_queue_connect__method__Runtime(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueConnectMethodRuntimeConstMeta,
      argValues: [that, ip],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueConnectMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_connect__method__Runtime",
        argNames: ["that", "ip"],
      );

  Future<void> queueDropMethodRuntime(
      {required Runtime that, required List<Ipv4AddrWrap> ips, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_runtime(that);
    var arg1 = _platform.api2wire_list_ipv_4_addr_wrap(ips);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_queue_drop__method__Runtime(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kQueueDropMethodRuntimeConstMeta,
      argValues: [that, ips],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueueDropMethodRuntimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "queue_drop__method__Runtime",
        argNames: ["that", "ips"],
      );

  DropFnType get dropOpaqueMutexModel => _platform.inner.drop_opaque_MutexModel;
  ShareFnType get shareOpaqueMutexModel =>
      _platform.inner.share_opaque_MutexModel;
  OpaqueTypeFinalizer get MutexModelFinalizer => _platform.MutexModelFinalizer;

  DropFnType get dropOpaqueMutexOptionHandle =>
      _platform.inner.drop_opaque_MutexOptionHandle;
  ShareFnType get shareOpaqueMutexOptionHandle =>
      _platform.inner.share_opaque_MutexOptionHandle;
  OpaqueTypeFinalizer get MutexOptionHandleFinalizer =>
      _platform.MutexOptionHandleFinalizer;

  DropFnType get dropOpaqueMutexOptionMpscReceiverAction =>
      _platform.inner.drop_opaque_MutexOptionMpscReceiverAction;
  ShareFnType get shareOpaqueMutexOptionMpscReceiverAction =>
      _platform.inner.share_opaque_MutexOptionMpscReceiverAction;
  OpaqueTypeFinalizer get MutexOptionMpscReceiverActionFinalizer =>
      _platform.MutexOptionMpscReceiverActionFinalizer;

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  Duration _wire2api_Chrono_Duration(dynamic raw) {
    return wire2apiDuration(_wire2api_i64(raw));
  }

  DateTime _wire2api_Chrono_Naive(dynamic raw) {
    return wire2apiTimestamp(ts: _wire2api_i64(raw), isUtc: true);
  }

  MutexModel _wire2api_MutexModel(dynamic raw) {
    return MutexModel.fromRaw(raw[0], raw[1], this);
  }

  MutexOptionHandle _wire2api_MutexOptionHandle(dynamic raw) {
    return MutexOptionHandle.fromRaw(raw[0], raw[1], this);
  }

  MutexOptionMpscReceiverAction _wire2api_MutexOptionMpscReceiverAction(
      dynamic raw) {
    return MutexOptionMpscReceiverAction.fromRaw(raw[0], raw[1], this);
  }

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  (String, String) _wire2api___record__String_String(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      _wire2api_String(arr[0]),
      _wire2api_String(arr[1]),
    );
  }

  Balance _wire2api_balance(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Balance(
      field0: _wire2api_f64(arr[0]),
    );
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  DetailDailyWrap _wire2api_box_autoadd_detail_daily_wrap(dynamic raw) {
    return _wire2api_detail_daily_wrap(raw);
  }

  NetFlux _wire2api_box_autoadd_net_flux(dynamic raw) {
    return _wire2api_net_flux(raw);
  }

  DetailDailyPoint _wire2api_detail_daily_point(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DetailDailyPoint(
      day: _wire2api_u32(arr[0]),
      flux: _wire2api_flux(arr[1]),
    );
  }

  DetailDailyWrap _wire2api_detail_daily_wrap(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DetailDailyWrap(
      details: _wire2api_list_detail_daily_point(arr[0]),
      nowMonth: _wire2api_u32(arr[1]),
      nowDay: _wire2api_u32(arr[2]),
      maxFlux: _wire2api_flux(arr[3]),
    );
  }

  double _wire2api_f64(dynamic raw) {
    return raw as double;
  }

  Flux _wire2api_flux(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Flux(
      field0: _wire2api_u64(arr[0]),
    );
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_i64(dynamic raw) {
    return castInt(raw);
  }

  Ipv4AddrWrap _wire2api_ipv_4_addr_wrap(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Ipv4AddrWrap(
      octets: _wire2api_u8_array_4(arr[0]),
    );
  }

  List<DetailDailyPoint> _wire2api_list_detail_daily_point(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_detail_daily_point).toList();
  }

  List<NetDetail> _wire2api_list_net_detail(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_net_detail).toList();
  }

  List<NetUserWrap> _wire2api_list_net_user_wrap(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_net_user_wrap).toList();
  }

  NetDateTime _wire2api_net_date_time(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return NetDateTime(
      field0: _wire2api_Chrono_Naive(arr[0]),
    );
  }

  NetDetail _wire2api_net_detail(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NetDetail(
      loginTime: _wire2api_net_date_time(arr[0]),
      logoutTime: _wire2api_net_date_time(arr[1]),
      flux: _wire2api_flux(arr[2]),
    );
  }

  NetFlux _wire2api_net_flux(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NetFlux(
      username: _wire2api_String(arr[0]),
      flux: _wire2api_flux(arr[1]),
      onlineTime: _wire2api_new_duration(arr[2]),
      balance: _wire2api_balance(arr[3]),
    );
  }

  NetState _wire2api_net_state(dynamic raw) {
    return NetState.values[raw as int];
  }

  NetStatus _wire2api_net_status(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return NetStatus_Unknown();
      case 1:
        return NetStatus_Wwan();
      case 2:
        return NetStatus_Wlan(
          _wire2api_String(raw[1]),
        );
      case 3:
        return NetStatus_Lan();
      default:
        throw Exception("unreachable");
    }
  }

  NetUserWrap _wire2api_net_user_wrap(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NetUserWrap(
      address: _wire2api_ipv_4_addr_wrap(arr[0]),
      loginTime: _wire2api_net_date_time(arr[1]),
      macAddress: _wire2api_String(arr[2]),
      flux: _wire2api_flux(arr[3]),
      isLocal: _wire2api_bool(arr[4]),
    );
  }

  NewDuration _wire2api_new_duration(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return NewDuration(
      field0: _wire2api_Chrono_Duration(arr[0]),
    );
  }

  Runtime _wire2api_runtime(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Runtime(
      bridge: this,
      rx: _wire2api_MutexOptionMpscReceiverAction(arr[0]),
      model: _wire2api_MutexModel(arr[1]),
      handle: _wire2api_MutexOptionHandle(arr[2]),
    );
  }

  int _wire2api_u32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  U8Array4 _wire2api_u8_array_4(dynamic raw) {
    return U8Array4(_wire2api_uint_8_list(raw));
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }

  UpdateMsgWrap _wire2api_update_msg_wrap(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return UpdateMsgWrap_Credential(
          _wire2api_String(raw[1]),
        );
      case 1:
        return UpdateMsgWrap_State(
          _wire2api_net_state(raw[1]),
        );
      case 2:
        return UpdateMsgWrap_Status(
          _wire2api_String(raw[1]),
        );
      case 3:
        return UpdateMsgWrap_Log(
          _wire2api_String(raw[1]),
        );
      case 4:
        return UpdateMsgWrap_Flux(
          _wire2api_box_autoadd_net_flux(raw[1]),
        );
      case 5:
        return UpdateMsgWrap_Online(
          _wire2api_list_net_user_wrap(raw[1]),
        );
      case 6:
        return UpdateMsgWrap_Details(
          _wire2api_list_net_detail(raw[1]),
          _wire2api_box_autoadd_detail_daily_wrap(raw[2]),
        );
      case 7:
        return UpdateMsgWrap_LogBusy(
          _wire2api_bool(raw[1]),
        );
      case 8:
        return UpdateMsgWrap_OnlineBusy(
          _wire2api_bool(raw[1]),
        );
      case 9:
        return UpdateMsgWrap_DetailBusy(
          _wire2api_bool(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }
}

// Section: api2wire

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_net_state(NetState raw) {
  return api2wire_i32(raw.index);
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class NativePlatform extends FlutterRustBridgeBase<NativeWire> {
  NativePlatform(ffi.DynamicLibrary dylib) : super(NativeWire(dylib));

// Section: api2wire

  @protected
  wire_MutexModel api2wire_MutexModel(MutexModel raw) {
    final ptr = inner.new_MutexModel();
    _api_fill_to_wire_MutexModel(raw, ptr);
    return ptr;
  }

  @protected
  wire_MutexOptionHandle api2wire_MutexOptionHandle(MutexOptionHandle raw) {
    final ptr = inner.new_MutexOptionHandle();
    _api_fill_to_wire_MutexOptionHandle(raw, ptr);
    return ptr;
  }

  @protected
  wire_MutexOptionMpscReceiverAction api2wire_MutexOptionMpscReceiverAction(
      MutexOptionMpscReceiverAction raw) {
    final ptr = inner.new_MutexOptionMpscReceiverAction();
    _api_fill_to_wire_MutexOptionMpscReceiverAction(raw, ptr);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_Ipv4AddrWrap> api2wire_box_autoadd_ipv_4_addr_wrap(
      Ipv4AddrWrap raw) {
    final ptr = inner.new_box_autoadd_ipv_4_addr_wrap_0();
    _api_fill_to_wire_ipv_4_addr_wrap(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> api2wire_box_autoadd_net_state(NetState raw) {
    return inner.new_box_autoadd_net_state_0(api2wire_net_state(raw));
  }

  @protected
  ffi.Pointer<wire_NetStatus> api2wire_box_autoadd_net_status(NetStatus raw) {
    final ptr = inner.new_box_autoadd_net_status_0();
    _api_fill_to_wire_net_status(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Runtime> api2wire_box_autoadd_runtime(Runtime raw) {
    final ptr = inner.new_box_autoadd_runtime_0();
    _api_fill_to_wire_runtime(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_RuntimeStartConfig>
      api2wire_box_autoadd_runtime_start_config(RuntimeStartConfig raw) {
    final ptr = inner.new_box_autoadd_runtime_start_config_0();
    _api_fill_to_wire_runtime_start_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_list_ipv_4_addr_wrap> api2wire_list_ipv_4_addr_wrap(
      List<Ipv4AddrWrap> raw) {
    final ans = inner.new_list_ipv_4_addr_wrap_0(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      _api_fill_to_wire_ipv_4_addr_wrap(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<ffi.Int32> api2wire_opt_box_autoadd_net_state(NetState? raw) {
    return raw == null ? ffi.nullptr : api2wire_box_autoadd_net_state(raw);
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_u8_array_4(U8Array4 raw) {
    final ans = inner.new_uint_8_list_0(4);
    ans.ref.ptr.asTypedList(4).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

  late final OpaqueTypeFinalizer _MutexModelFinalizer =
      OpaqueTypeFinalizer(inner._drop_opaque_MutexModelPtr);
  OpaqueTypeFinalizer get MutexModelFinalizer => _MutexModelFinalizer;
  late final OpaqueTypeFinalizer _MutexOptionHandleFinalizer =
      OpaqueTypeFinalizer(inner._drop_opaque_MutexOptionHandlePtr);
  OpaqueTypeFinalizer get MutexOptionHandleFinalizer =>
      _MutexOptionHandleFinalizer;
  late final OpaqueTypeFinalizer _MutexOptionMpscReceiverActionFinalizer =
      OpaqueTypeFinalizer(inner._drop_opaque_MutexOptionMpscReceiverActionPtr);
  OpaqueTypeFinalizer get MutexOptionMpscReceiverActionFinalizer =>
      _MutexOptionMpscReceiverActionFinalizer;
// Section: api_fill_to_wire

  void _api_fill_to_wire_MutexModel(
      MutexModel apiObj, wire_MutexModel wireObj) {
    wireObj.ptr = apiObj.shareOrMove();
  }

  void _api_fill_to_wire_MutexOptionHandle(
      MutexOptionHandle apiObj, wire_MutexOptionHandle wireObj) {
    wireObj.ptr = apiObj.shareOrMove();
  }

  void _api_fill_to_wire_MutexOptionMpscReceiverAction(
      MutexOptionMpscReceiverAction apiObj,
      wire_MutexOptionMpscReceiverAction wireObj) {
    wireObj.ptr = apiObj.shareOrMove();
  }

  void _api_fill_to_wire_box_autoadd_ipv_4_addr_wrap(
      Ipv4AddrWrap apiObj, ffi.Pointer<wire_Ipv4AddrWrap> wireObj) {
    _api_fill_to_wire_ipv_4_addr_wrap(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_net_status(
      NetStatus apiObj, ffi.Pointer<wire_NetStatus> wireObj) {
    _api_fill_to_wire_net_status(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_runtime(
      Runtime apiObj, ffi.Pointer<wire_Runtime> wireObj) {
    _api_fill_to_wire_runtime(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_runtime_start_config(
      RuntimeStartConfig apiObj, ffi.Pointer<wire_RuntimeStartConfig> wireObj) {
    _api_fill_to_wire_runtime_start_config(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_ipv_4_addr_wrap(
      Ipv4AddrWrap apiObj, wire_Ipv4AddrWrap wireObj) {
    wireObj.octets = api2wire_u8_array_4(apiObj.octets);
  }

  void _api_fill_to_wire_net_status(NetStatus apiObj, wire_NetStatus wireObj) {
    if (apiObj is NetStatus_Unknown) {
      wireObj.tag = 0;
      return;
    }
    if (apiObj is NetStatus_Wwan) {
      wireObj.tag = 1;
      return;
    }
    if (apiObj is NetStatus_Wlan) {
      var pre_field0 = api2wire_String(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind = inner.inflate_NetStatus_Wlan();
      wireObj.kind.ref.Wlan.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is NetStatus_Lan) {
      wireObj.tag = 3;
      return;
    }
  }

  void _api_fill_to_wire_runtime(Runtime apiObj, wire_Runtime wireObj) {
    wireObj.rx = api2wire_MutexOptionMpscReceiverAction(apiObj.rx);
    wireObj.model = api2wire_MutexModel(apiObj.model);
    wireObj.handle = api2wire_MutexOptionHandle(apiObj.handle);
  }

  void _api_fill_to_wire_runtime_start_config(
      RuntimeStartConfig apiObj, wire_RuntimeStartConfig wireObj) {
    _api_fill_to_wire_net_status(apiObj.status, wireObj.status);
    wireObj.username = api2wire_String(apiObj.username);
    wireObj.password = api2wire_String(apiObj.password);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class NativeWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_new__static_method__Runtime(
    int port_,
  ) {
    return _wire_new__static_method__Runtime(
      port_,
    );
  }

  late final _wire_new__static_method__RuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_new__static_method__Runtime');
  late final _wire_new__static_method__Runtime =
      _wire_new__static_method__RuntimePtr.asFunction<void Function(int)>();

  void wire_start__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<wire_RuntimeStartConfig> config,
  ) {
    return _wire_start__method__Runtime(
      port_,
      that,
      config,
    );
  }

  late final _wire_start__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>,
                  ffi.Pointer<wire_RuntimeStartConfig>)>>(
      'wire_start__method__Runtime');
  late final _wire_start__method__Runtime =
      _wire_start__method__RuntimePtr.asFunction<
          void Function(int, ffi.Pointer<wire_Runtime>,
              ffi.Pointer<wire_RuntimeStartConfig>)>();

  void wire_current_status__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_current_status__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_current_status__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>)>>(
      'wire_current_status__method__Runtime');
  late final _wire_current_status__method__Runtime =
      _wire_current_status__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_load_credential__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_load_credential__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_load_credential__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>)>>(
      'wire_load_credential__method__Runtime');
  late final _wire_load_credential__method__Runtime =
      _wire_load_credential__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_save_credential__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<wire_uint_8_list> u,
    ffi.Pointer<wire_uint_8_list> p,
  ) {
    return _wire_save_credential__method__Runtime(
      port_,
      that,
      u,
      p,
    );
  }

  late final _wire_save_credential__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_Runtime>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>)>>(
      'wire_save_credential__method__Runtime');
  late final _wire_save_credential__method__Runtime =
      _wire_save_credential__method__RuntimePtr.asFunction<
          void Function(int, ffi.Pointer<wire_Runtime>,
              ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_queue_credential__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<wire_uint_8_list> u,
    ffi.Pointer<wire_uint_8_list> p,
  ) {
    return _wire_queue_credential__method__Runtime(
      port_,
      that,
      u,
      p,
    );
  }

  late final _wire_queue_credential__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_Runtime>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>)>>(
      'wire_queue_credential__method__Runtime');
  late final _wire_queue_credential__method__Runtime =
      _wire_queue_credential__method__RuntimePtr.asFunction<
          void Function(int, ffi.Pointer<wire_Runtime>,
              ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_queue_login__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_queue_login__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_queue_login__method__RuntimePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_Runtime>)>>('wire_queue_login__method__Runtime');
  late final _wire_queue_login__method__Runtime =
      _wire_queue_login__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_queue_logout__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_queue_logout__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_queue_logout__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>)>>(
      'wire_queue_logout__method__Runtime');
  late final _wire_queue_logout__method__Runtime =
      _wire_queue_logout__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_queue_flux__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_queue_flux__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_queue_flux__method__RuntimePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_Runtime>)>>('wire_queue_flux__method__Runtime');
  late final _wire_queue_flux__method__Runtime =
      _wire_queue_flux__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_queue_state__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<ffi.Int32> s,
  ) {
    return _wire_queue_state__method__Runtime(
      port_,
      that,
      s,
    );
  }

  late final _wire_queue_state__method__RuntimePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>,
              ffi.Pointer<ffi.Int32>)>>('wire_queue_state__method__Runtime');
  late final _wire_queue_state__method__Runtime =
      _wire_queue_state__method__RuntimePtr.asFunction<
          void Function(
              int, ffi.Pointer<wire_Runtime>, ffi.Pointer<ffi.Int32>)>();

  void wire_queue_status__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<wire_NetStatus> s,
  ) {
    return _wire_queue_status__method__Runtime(
      port_,
      that,
      s,
    );
  }

  late final _wire_queue_status__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>,
                  ffi.Pointer<wire_NetStatus>)>>(
      'wire_queue_status__method__Runtime');
  late final _wire_queue_status__method__Runtime =
      _wire_queue_status__method__RuntimePtr.asFunction<
          void Function(
              int, ffi.Pointer<wire_Runtime>, ffi.Pointer<wire_NetStatus>)>();

  void wire_queue_details__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_queue_details__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_queue_details__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>)>>(
      'wire_queue_details__method__Runtime');
  late final _wire_queue_details__method__Runtime =
      _wire_queue_details__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_queue_onlines__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
  ) {
    return _wire_queue_onlines__method__Runtime(
      port_,
      that,
    );
  }

  late final _wire_queue_onlines__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>)>>(
      'wire_queue_onlines__method__Runtime');
  late final _wire_queue_onlines__method__Runtime =
      _wire_queue_onlines__method__RuntimePtr
          .asFunction<void Function(int, ffi.Pointer<wire_Runtime>)>();

  void wire_queue_connect__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<wire_Ipv4AddrWrap> ip,
  ) {
    return _wire_queue_connect__method__Runtime(
      port_,
      that,
      ip,
    );
  }

  late final _wire_queue_connect__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>,
                  ffi.Pointer<wire_Ipv4AddrWrap>)>>(
      'wire_queue_connect__method__Runtime');
  late final _wire_queue_connect__method__Runtime =
      _wire_queue_connect__method__RuntimePtr.asFunction<
          void Function(int, ffi.Pointer<wire_Runtime>,
              ffi.Pointer<wire_Ipv4AddrWrap>)>();

  void wire_queue_drop__method__Runtime(
    int port_,
    ffi.Pointer<wire_Runtime> that,
    ffi.Pointer<wire_list_ipv_4_addr_wrap> ips,
  ) {
    return _wire_queue_drop__method__Runtime(
      port_,
      that,
      ips,
    );
  }

  late final _wire_queue_drop__method__RuntimePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Runtime>,
                  ffi.Pointer<wire_list_ipv_4_addr_wrap>)>>(
      'wire_queue_drop__method__Runtime');
  late final _wire_queue_drop__method__Runtime =
      _wire_queue_drop__method__RuntimePtr.asFunction<
          void Function(int, ffi.Pointer<wire_Runtime>,
              ffi.Pointer<wire_list_ipv_4_addr_wrap>)>();

  wire_MutexModel new_MutexModel() {
    return _new_MutexModel();
  }

  late final _new_MutexModelPtr =
      _lookup<ffi.NativeFunction<wire_MutexModel Function()>>('new_MutexModel');
  late final _new_MutexModel =
      _new_MutexModelPtr.asFunction<wire_MutexModel Function()>();

  wire_MutexOptionHandle new_MutexOptionHandle() {
    return _new_MutexOptionHandle();
  }

  late final _new_MutexOptionHandlePtr =
      _lookup<ffi.NativeFunction<wire_MutexOptionHandle Function()>>(
          'new_MutexOptionHandle');
  late final _new_MutexOptionHandle =
      _new_MutexOptionHandlePtr.asFunction<wire_MutexOptionHandle Function()>();

  wire_MutexOptionMpscReceiverAction new_MutexOptionMpscReceiverAction() {
    return _new_MutexOptionMpscReceiverAction();
  }

  late final _new_MutexOptionMpscReceiverActionPtr = _lookup<
          ffi.NativeFunction<wire_MutexOptionMpscReceiverAction Function()>>(
      'new_MutexOptionMpscReceiverAction');
  late final _new_MutexOptionMpscReceiverAction =
      _new_MutexOptionMpscReceiverActionPtr
          .asFunction<wire_MutexOptionMpscReceiverAction Function()>();

  ffi.Pointer<wire_Ipv4AddrWrap> new_box_autoadd_ipv_4_addr_wrap_0() {
    return _new_box_autoadd_ipv_4_addr_wrap_0();
  }

  late final _new_box_autoadd_ipv_4_addr_wrap_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_Ipv4AddrWrap> Function()>>(
          'new_box_autoadd_ipv_4_addr_wrap_0');
  late final _new_box_autoadd_ipv_4_addr_wrap_0 =
      _new_box_autoadd_ipv_4_addr_wrap_0Ptr
          .asFunction<ffi.Pointer<wire_Ipv4AddrWrap> Function()>();

  ffi.Pointer<ffi.Int32> new_box_autoadd_net_state_0(
    int value,
  ) {
    return _new_box_autoadd_net_state_0(
      value,
    );
  }

  late final _new_box_autoadd_net_state_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
          'new_box_autoadd_net_state_0');
  late final _new_box_autoadd_net_state_0 = _new_box_autoadd_net_state_0Ptr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<wire_NetStatus> new_box_autoadd_net_status_0() {
    return _new_box_autoadd_net_status_0();
  }

  late final _new_box_autoadd_net_status_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_NetStatus> Function()>>(
          'new_box_autoadd_net_status_0');
  late final _new_box_autoadd_net_status_0 = _new_box_autoadd_net_status_0Ptr
      .asFunction<ffi.Pointer<wire_NetStatus> Function()>();

  ffi.Pointer<wire_Runtime> new_box_autoadd_runtime_0() {
    return _new_box_autoadd_runtime_0();
  }

  late final _new_box_autoadd_runtime_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_Runtime> Function()>>(
          'new_box_autoadd_runtime_0');
  late final _new_box_autoadd_runtime_0 = _new_box_autoadd_runtime_0Ptr
      .asFunction<ffi.Pointer<wire_Runtime> Function()>();

  ffi.Pointer<wire_RuntimeStartConfig>
      new_box_autoadd_runtime_start_config_0() {
    return _new_box_autoadd_runtime_start_config_0();
  }

  late final _new_box_autoadd_runtime_start_config_0Ptr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_RuntimeStartConfig> Function()>>(
      'new_box_autoadd_runtime_start_config_0');
  late final _new_box_autoadd_runtime_start_config_0 =
      _new_box_autoadd_runtime_start_config_0Ptr
          .asFunction<ffi.Pointer<wire_RuntimeStartConfig> Function()>();

  ffi.Pointer<wire_list_ipv_4_addr_wrap> new_list_ipv_4_addr_wrap_0(
    int len,
  ) {
    return _new_list_ipv_4_addr_wrap_0(
      len,
    );
  }

  late final _new_list_ipv_4_addr_wrap_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_list_ipv_4_addr_wrap> Function(
              ffi.Int32)>>('new_list_ipv_4_addr_wrap_0');
  late final _new_list_ipv_4_addr_wrap_0 = _new_list_ipv_4_addr_wrap_0Ptr
      .asFunction<ffi.Pointer<wire_list_ipv_4_addr_wrap> Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void drop_opaque_MutexModel(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _drop_opaque_MutexModel(
      ptr,
    );
  }

  late final _drop_opaque_MutexModelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'drop_opaque_MutexModel');
  late final _drop_opaque_MutexModel = _drop_opaque_MutexModelPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> share_opaque_MutexModel(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _share_opaque_MutexModel(
      ptr,
    );
  }

  late final _share_opaque_MutexModelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>)>>('share_opaque_MutexModel');
  late final _share_opaque_MutexModel = _share_opaque_MutexModelPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  void drop_opaque_MutexOptionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _drop_opaque_MutexOptionHandle(
      ptr,
    );
  }

  late final _drop_opaque_MutexOptionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'drop_opaque_MutexOptionHandle');
  late final _drop_opaque_MutexOptionHandle = _drop_opaque_MutexOptionHandlePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> share_opaque_MutexOptionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _share_opaque_MutexOptionHandle(
      ptr,
    );
  }

  late final _share_opaque_MutexOptionHandlePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>)>>('share_opaque_MutexOptionHandle');
  late final _share_opaque_MutexOptionHandle =
      _share_opaque_MutexOptionHandlePtr
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  void drop_opaque_MutexOptionMpscReceiverAction(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _drop_opaque_MutexOptionMpscReceiverAction(
      ptr,
    );
  }

  late final _drop_opaque_MutexOptionMpscReceiverActionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'drop_opaque_MutexOptionMpscReceiverAction');
  late final _drop_opaque_MutexOptionMpscReceiverAction =
      _drop_opaque_MutexOptionMpscReceiverActionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> share_opaque_MutexOptionMpscReceiverAction(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _share_opaque_MutexOptionMpscReceiverAction(
      ptr,
    );
  }

  late final _share_opaque_MutexOptionMpscReceiverActionPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>>(
      'share_opaque_MutexOptionMpscReceiverAction');
  late final _share_opaque_MutexOptionMpscReceiverAction =
      _share_opaque_MutexOptionMpscReceiverActionPtr
          .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<NetStatusKind> inflate_NetStatus_Wlan() {
    return _inflate_NetStatus_Wlan();
  }

  late final _inflate_NetStatus_WlanPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<NetStatusKind> Function()>>(
          'inflate_NetStatus_Wlan');
  late final _inflate_NetStatus_Wlan = _inflate_NetStatus_WlanPtr
      .asFunction<ffi.Pointer<NetStatusKind> Function()>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_MutexOptionMpscReceiverAction extends ffi.Struct {
  external ffi.Pointer<ffi.Void> ptr;
}

final class wire_MutexModel extends ffi.Struct {
  external ffi.Pointer<ffi.Void> ptr;
}

final class wire_MutexOptionHandle extends ffi.Struct {
  external ffi.Pointer<ffi.Void> ptr;
}

final class wire_Runtime extends ffi.Struct {
  external wire_MutexOptionMpscReceiverAction rx;

  external wire_MutexModel model;

  external wire_MutexOptionHandle handle;
}

final class wire_NetStatus_Unknown extends ffi.Opaque {}

final class wire_NetStatus_Wwan extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_NetStatus_Wlan extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> field0;
}

final class wire_NetStatus_Lan extends ffi.Opaque {}

final class NetStatusKind extends ffi.Union {
  external ffi.Pointer<wire_NetStatus_Unknown> Unknown;

  external ffi.Pointer<wire_NetStatus_Wwan> Wwan;

  external ffi.Pointer<wire_NetStatus_Wlan> Wlan;

  external ffi.Pointer<wire_NetStatus_Lan> Lan;
}

final class wire_NetStatus extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<NetStatusKind> kind;
}

final class wire_RuntimeStartConfig extends ffi.Struct {
  external wire_NetStatus status;

  external ffi.Pointer<wire_uint_8_list> username;

  external ffi.Pointer<wire_uint_8_list> password;
}

final class wire_Ipv4AddrWrap extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> octets;
}

final class wire_list_ipv_4_addr_wrap extends ffi.Struct {
  external ffi.Pointer<wire_Ipv4AddrWrap> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
