import { AboutSlint, HorizontalBox, StandardTableView, VerticalBox } from "std-widgets.slint";

export global AboutModel {
    in property <string> version: "0.0.0";

    in property <[[StandardListViewItem]]> deps: [
        [ { text: "anyhow" }, { text: "MIT"} ],
        [ { text: "async-stream" }, { text: "MIT"} ],
        [ { text: "chrono" }, { text: "MIT"} ],
        [ { text: "clap" }, { text: "MIT"} ],
        [ { text: "console" }, { text: "MIT"} ],
        [ { text: "core-foundation" }, { text: "MIT"} ],
        [ { text: "crossterm" }, { text: "MIT"} ],
        [ { text: "data-encoding" }, { text: "MIT"} ],
        [ { text: "data-encoding-macro" }, { text: "MIT"} ],
        [ { text: "dirs" }, { text: "MIT"} ],
        [ { text: "enum_dispatch" }, { text: "MIT"} ],
        [ { text: "futures-core" }, { text: "MIT"} ],
        [ { text: "futures-util" }, { text: "MIT"} ],
        [ { text: "hmac" }, { text: "MIT"} ],
        [ { text: "humantime" }, { text: "MIT"} ],
        [ { text: "image" }, { text: "MIT"} ],
        [ { text: "is_elevated" }, { text: "MIT"} ],
        [ { text: "itertools" }, { text: "MIT"} ],
        [ { text: "keyring" }, { text: "MIT"} ],
        [ { text: "libc" }, { text: "MIT"} ],
        [ { text: "mac_address2" }, { text: "MIT"} ],
        [ { text: "md-5" }, { text: "MIT"} ],
        [ { text: "netlink_wi" }, { text: "MIT"} ],
        [ { text: "notify-rust" }, { text: "MIT"} ],
        [ { text: "objc" }, { text: "MIT"} ],
        [ { text: "once_cell" }, { text: "MIT"} ],
        [ { text: "paste" }, { text: "MIT"} ],
        [ { text: "plist" }, { text: "MIT"} ],
        [ { text: "plotters" }, { text: "MIT"} ],
        [ { text: "ratatui" }, { text: "MIT"} ],
        [ { text: "regex" }, { text: "MIT"} ],
        [ { text: "reqwest" }, { text: "MIT"} ],
        [ { text: "rpassword" }, { text: "Apache-2.0"} ],
        [ { text: "select" }, { text: "MIT"} ],
        [ { text: "serde" }, { text: "MIT"} ],
        [ { text: "serde_json" }, { text: "MIT"} ],
        [ { text: "sha-1" }, { text: "MIT"} ],
        [ { text: "slint" }, { text: "GPL-3.0"} ],
        [ { text: "subprocess" }, { text: "MIT"} ],
        [ { text: "system-configuration" }, { text: "MIT"} ],
        [ { text: "thiserror" }, { text: "MIT"} ],
        [ { text: "tokio" }, { text: "MIT"} ],
        [ { text: "tokio-stream" }, { text: "MIT"} ],
        [ { text: "url" }, { text: "MIT"} ],
        [ { text: "widestring" }, { text: "MIT"} ],
        [ { text: "windows" }, { text: "MIT"} ],
        [ { text: "windows-service" }, { text: "MIT"} ],
    ];
    callback sort_ascending(int);
    callback sort_descending(int);
}

export component AboutPage inherits VerticalBox {
    HorizontalBox {
        VerticalBox {
            Text {
                text: "清华大学校园网客户端";
                horizontal-alignment: center;
                font-size: 1.5rem;
                font-weight: 700;
            }
            Text {
                text: "版本 " + AboutModel.version;
                horizontal-alignment: center;
            }
            Text {
                text: "版权所有 © 2021-2023 Berrysoft";
                horizontal-alignment: center;
            }
            Text {
                text: "服务热线（8:00~20:00）010-62784859";
                horizontal-alignment: center;
            }
            Rectangle {}
        }
        AboutSlint {}
    }
    VerticalBox {
        Text {
            text: "使用的库";
            horizontal-alignment: center;
            font-size: 1.5rem;
            font-weight: 700;
        }
        StandardTableView {
            columns: [
                { title: "名称" },
                { title: "许可证" },
            ];
            rows: AboutModel.deps;
            sort-ascending(index) => {
                AboutModel.sort_ascending(index);
            }
            sort-descending(index) => {
                AboutModel.sort-descending(index);
            }
        }
    }
}
