import { TabWidget, VerticalBox } from "std-widgets.slint";
import { HomePage, NetInfo, HomeModel } from "home.slint";
import { SettingsPage, SettingsModel } from "settings.slint";
import { AboutPage, AboutModel } from "about.slint";

export { NetInfo, HomeModel, SettingsModel, AboutModel }

export component App inherits Window {
    default-font-size: 16px;

    preferred-width: 600px;
    preferred-height: 600px;
    title: "清华校园网";
    icon: @image-url("../../logo.png");

    HorizontalLayout {
        TabWidget {
            Tab {
                title: "主页";
                HomePage {}
            }
            Tab {
                title: "设置";
                SettingsPage {}
            }
            Tab {
                title: "关于";
                AboutPage {}
            }
        }
    }
}
