import { Button, HorizontalBox, StandardButton, StandardTableView, VerticalBox } from "std-widgets.slint";

export global SettingsModel {
    in property <string> username;
    in property <string> status;

    in property <bool> busy;

    callback set_credential(string, string);

    callback del_and_exit();

    in property <[[StandardListViewItem]]> onlines: [];
    callback refresh();

    callback connect_ip(string);
    callback drop_ip(string);
}

export component SettingsPage inherits VerticalBox {
    Text {
        text: "当前凭据";
        horizontal-alignment: center;
        font-size: 20px;
        font-weight: 700;
    }
    Text {
        text: SettingsModel.username != "" ? "用户：" + SettingsModel.username : "";
        horizontal-alignment: center;
    }
    HorizontalBox {
        Button {
            text: "设置";
            enabled: false;
        }
        del_at_exit_btn := Button {
            text: "删除并退出";
            clicked => { msgbox.show() }
        }
        msgbox := PopupWindow {
            x: del_at_exit_btn.x;
            y: del_at_exit_btn.y + del_at_exit_btn.height;
            Rectangle {
                background: confirm_layout.background;
            }
            confirm_layout := Dialog {
                width: 100%;
                height: 100%;
                title: "删除凭据并退出";
                Text {
                    text: "删除后程序将会退出。";
                }
                StandardButton { kind: yes; clicked => { SettingsModel.del_and_exit() } }
            }
        }
    }
    Text {
        text: "网络状态";
        horizontal-alignment: center;
        font-size: 20px;
        font-weight: 700;
    }
    Text {
        text: SettingsModel.status;
        horizontal-alignment: center;
    }
    VerticalBox {
        Text {
            text: "管理连接";
            horizontal-alignment: center;
            font-size: 20px;
            font-weight: 700;
        }
        StandardTableView {
            columns: [
                { title: "IP地址" },
                { title: "登录时间" },
                { title: "流量" },
                { title: "MAC地址" },
                { title: "设备" },
            ];
            rows: SettingsModel.onlines;
        }
    }
    HorizontalBox {
        Button {
            text: "认证IP";
            enabled: false;
        }
        Button {
            text: "下线IP";
            enabled: false;
        }
        Button {
            text: "刷新";
            enabled: !SettingsModel.busy;
            clicked => { SettingsModel.refresh() }
        }
    }
}
