[package]
name = "tunet-native"
version = "0.5.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tunet-rust = { path = "../tunet-rust" }
lazy_static = "1.4"
