[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
strip = { path = "aarch64-linux-gnu-strip" }
objcopy = { path = "aarch64-linux-gnu-objcopy" }

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"
strip = { path = "riscv64-linux-gnu-strip" }
objcopy = { path = "riscv64-linux-gnu-objcopy" }
