import { AboutSlint, HorizontalBox, VerticalBox } from "std-widgets.slint";

export global AboutModel {
    in property <string> version: "0.0.0";
}

export component AboutPage inherits VerticalBox {
    HorizontalBox {
        VerticalBox {
            Text {
                text: "清华大学校园网客户端";
                horizontal-alignment: center;
                font-size: 20px;
                font-weight: 700;
            }
            Text {
                text: "版本 " + AboutModel.version;
                horizontal-alignment: center;
            }
        }
        //AboutSlint {}
    }
}
