import { Button, StyleMetrics, VerticalBox } from "std-widgets.slint";
import { DetailModel } from "detail.slint";

export global ChartModel {
    out property <bool> dark: StyleMetrics.dark-color-scheme;
    in property <image> daily-chart;
}

export component ChartPage inherits VerticalBox {
    VerticalBox {
        Image {
            source: ChartModel.daily-chart;
        }
        Button {
            text: "刷新";
            enabled: !DetailModel.busy;
            clicked => { DetailModel.refresh() }
        }
    }
}
