import { Button, VerticalBox } from "std-widgets.slint";
import { DetailModel } from "detail.slint";

export global ChartModel {
    in property <image> time-chart;
    in property <image> daily-chart;
}

export component ChartPage inherits VerticalBox {
    VerticalBox {
        Image {
            source: ChartModel.time-chart;
        }
        Image {
            source: ChartModel.daily-chart;
        }
        Button {
            text: "刷新";
            enabled: !DetailModel.busy;
            clicked => { DetailModel.refresh() }
        }
    }
}
