import { TabWidget, VerticalBox } from "std-widgets.slint";
import { HomePage, NetInfo, HomeModel } from "home.slint";
import { AboutPage, AboutModel } from "about.slint";

export { NetInfo, HomeModel, AboutModel }

export component App inherits Window {
    preferred-width: 500px;
    preferred-height: 500px;
    title: "清华校园网";

    HorizontalLayout {
        TabWidget {
            Tab {
                title: "主页";
                HomePage {}
            }
            Tab {
                title: "关于";
                AboutPage {}
            }
        }
    }
}
