import { Button, HorizontalBox, StandardTableView, VerticalBox } from "std-widgets.slint";

export global SettingsModel {
    in property <string> username;
    in property <string> status;

    in property <bool> busy;

    in property <[[StandardListViewItem]]> onlines: [];
    callback refresh();
}

export component SettingsPage inherits VerticalBox {
    Text {
        text: "当前凭据";
        horizontal-alignment: center;
        font-size: 20px;
        font-weight: 700;
    }
    Text {
        text: SettingsModel.username != "" ? "用户：" + SettingsModel.username : "";
        horizontal-alignment: center;
    }
    HorizontalBox {
        Button {
            text: "设置";
        }
        Button {
            text: "删除并退出";
        }
    }
    Text {
        text: "网络状态";
        horizontal-alignment: center;
        font-size: 20px;
        font-weight: 700;
    }
    Text {
        text: SettingsModel.status;
        horizontal-alignment: center;
    }
    VerticalBox {
        Text {
            text: "管理连接";
            horizontal-alignment: center;
            font-size: 20px;
            font-weight: 700;
        }
        StandardTableView {
            columns: [
                { title: "IP地址" },
                { title: "登录时间" },
                { title: "流量" },
                { title: "MAC地址" },
                { title: "设备" },
            ];
            rows: SettingsModel.onlines;
        }
    }
    HorizontalBox {
        Button {
            text: "认证IP";
            enabled: !SettingsModel.busy;
        }
        Button {
            text: "下线IP";
            enabled: false;
        }
        Button {
            text: "刷新";
            enabled: !SettingsModel.busy;
            clicked => { SettingsModel.refresh() }
        }
    }
}
