[package]
name = "tunet-suggest"
version = "0.1.1"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
tunet-helper = { path = "../tunet-helper" }
netstatus = { path = "../netstatus" }
async-trait = "0.1"
once_cell = "1.17"
