[package]
name = "tunet"
version = "0.5.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
tunet-rust = { path = "../tunet-rust", features = [ "netstatus" ] }
keyring = { path = "../keyring" }
futures-util = "0.3"
tokio = { version = "1.11", features = [ "macros" ] }
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
trait_enum = "0.5"
anyhow = "1.0"
mac_address = "1.1"
structopt = "0.3"
itertools = "0.10"
termcolor = "1.1"
termcolor_output = { git = "https://github.com/Berrysoft/termcolor_output.git" }
rpassword = "5.0"
dirs = "4.0"

crossterm = { version = "0.20", optional = true }
tui = { version = "0.16", default-features = false, features = ['crossterm'], optional = true }
tokio-stream = { version = "0.1", optional = true }

[features]
default = [ "cui" ]
cui = [ "tui", "crossterm", "tokio/rt-multi-thread", "tokio/time", "tokio-stream" ]
