[package]
name = "tunet"
version = "0.6.2"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
tunet-helper = { path = "../tunet-helper" }
tunet-suggest = { path = "../tunet-suggest" }
tunet-settings-cli = { path = "../tunet-settings-cli" }
futures-util = "0.3"
tokio = { version = "1.14", features = [ "rt" ] }
async-trait = "0.1"
mac_address = "1.1"
clap = { version = "3.0", features = ["derive"] }
itertools = "0.10"
termcolor = "1.1"
termcolor_output = { git = "https://github.com/Berrysoft/termcolor_output.git" }
enum_dispatch = "0.3"
subprocess = "0.2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
