[package]
name = "tunet"
version = "0.12.0"
description = "Tsinghua University network CLI"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.deb]
assets = [
    [
        "target/release/tunet",
        "usr/bin/",
        "755",
    ],
    [
        "../logo.png",
        "usr/share/icons/hicolor/256x256/apps/tunet.png",
        "644",
    ],
    [
        "io.github.berrysoft.tunet.desktop",
        "usr/share/applications/io.github.berrysoft.tunet.desktop",
        "644",
    ],
    [
        "../tunet-service/tunet.service",
        "lib/systemd/user/tunet.service",
        "644",
    ],
]

[dependencies]
tunet-helper = { workspace = true }
tunet-settings = { workspace = true }
tunet-service = { workspace = true }
tunet-gui = { workspace = true }
anyhow = { workspace = true }
argh = { workspace = true }
cfg-if = { workspace = true }
compio = { workspace = true, features = ["macros"] }
console = "0.16"
enum_dispatch = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_System_Console"] }

ucrtbase = { version = "0.1.1", optional = true }

[target.'cfg(windows)'.build-dependencies]
winresource = { workspace = true }

[features]
default = ["win32"]
win32 = ["tunet-gui/win32"]
winui = ["tunet-gui/winui"]
objc-static = ["tunet-gui/objc-static"]

[package.metadata.winresource]
OriginalFilename = "tunet.exe"
LegalCopyright = "Copyright © 2021-2026 Berrysoft"
