[package]
name = "tunet"
version = "0.6.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
tunet-rust = { path = "../tunet-rust", features = [ "netstatus" ] }
tunet-settings = { path = "../tunet-settings" }
tunet-model = { path = "../tunet-model" }
futures-util = "0.3"
tokio = { version = "1.11", features = [ "rt", "macros" ] }
async-trait = "0.1"
anyhow = "1.0"
mac_address = "1.1"
structopt = "0.3"
itertools = "0.10"
termcolor = "1.1"
termcolor_output = { git = "https://github.com/Berrysoft/termcolor_output.git" }
rpassword = "5.0"

crossterm = { version = "0.20", optional = true, features = [ "event-stream" ] }
tui = { version = "0.16", default-features = false, features = [ "crossterm" ], optional = true }

[features]
default = [ "cui" ]
cui = [ "tui", "crossterm", "tokio/rt-multi-thread", "tokio/time" ]
