[package]
name = "tunet"
version = "0.6.3"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tunet-helper = { workspace = true }
tunet-suggest = { workspace = true }
tunet-settings-cli = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
async-trait = { workspace = true }
mac_address = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
termcolor = "1"
termcolor_output = { git = "https://github.com/Berrysoft/termcolor_output.git" }
enum_dispatch = { workspace = true }
subprocess = "0.2"

[target.'cfg(windows)'.build-dependencies]
winres = { workspace = true }
