[package]
name = "tunet"
version = "0.4.2"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
tunet-rust = { path = "../tunet-rust", features = [ "netstatus" ] }
serde = "1.0"
serde_json = "1.0"
mac_address = "1.1"
structopt = "0.3"
itertools = "0.10"
termcolor = "1.1"
termcolor_output = { git = "https://github.com/Berrysoft/termcolor_output.git" }
rpassword = "5.0"
dirs = "3.0"
