[package]
name = "tunet-rust"
version = "0.2.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
authtea = { path = "../authtea" }
rust-crypto = "0.2"
serde_json = "1.0"
rustc-serialize = "0.3"
select = "0.5"
chrono = "0.4"
hwaddr = { git = "https://github.com/meh/rust-hwaddr" }
lazy_static = "1.4"
regex = "1"

[dependencies.reqwest]
version = "0.10"
features = ["blocking"]
