[package]
name = "tunet-rust"
version = "0.2.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
authtea = { path = "../authtea" }
rust-crypto = "0.2"
serde_json = "1.0"
hex = "0.4"
select = "0.5"
chrono = "0.4"
hwaddr = { git = "https://github.com/meh/rust-hwaddr" }
lazy_static = "1.4"
regex = "1"
thiserror = "1.0"

[dependencies.reqwest]
version = "0.11"
features = [ "blocking", "cookies" ]
