[package]
name = "native"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tunet-helper = { workspace = true }
tunet-model = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
log = { workspace = true }
flutter_rust_bridge = "1"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
