[package]
name = "tunet-service"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
tunet-helper = { path = "../tunet-helper" }
tunet-suggest = { path = "../tunet-suggest" }
tunet-settings = { path = "../tunet-settings" }
tunet-settings-cli = { path = "../tunet-settings-cli" }
windows = { version = "0.48", features = [
    "Data_Xml_Dom",
    "Foundation",
    "Networking_Connectivity",
    "UI_Notifications",
    "Win32_Foundation",
    "Win32_System_Environment",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
widestring = "1.0"
tokio = { version = "1", features = ["macros", "rt", "signal", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
pin-project = "1.0"
clap = { version = "4", features = ["derive"] }
enum_dispatch = "0.3"
windows-service = "0.6"
is_elevated = "0.1"
once_cell = "1.17"
