[package]
name = "tunet-service"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tunet-helper = { workspace = true }
tunet-suggest = { workspace = true }
tunet-settings = { workspace = true }
tunet-settings-cli = { workspace = true }
windows = { workspace = true, features = [
    "Data_Xml_Dom",
    "Foundation",
    "Networking_Connectivity",
    "UI_Notifications",
    "Win32_Foundation",
    "Win32_System_Environment",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
widestring = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "signal", "sync"] }
tokio-stream = { workspace = true, features = ["sync"] }
pin-project = "1"
clap = { workspace = true }
humantime = "2"
enum_dispatch = { workspace = true }
windows-service = "0.6"
is_elevated = "0.1"
