[package]
name = "tunet-service"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tunet-helper = { workspace = true }
tunet-suggest = { workspace = true }
tunet-settings = { workspace = true }
tunet-settings-cli = { workspace = true }
cfg-if = { workspace = true }
clap = { workspace = true }
humantime = "2"
enum_dispatch = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "signal", "sync"] }
notify-rust = { version = "4", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Foundation",
    "Networking_Connectivity",
    "Win32_Foundation",
    "Win32_System_Environment",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
widestring = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }
pin-project = "1"
windows-service = "0.6"
is_elevated = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
system-configuration = "0.5"
core-foundation = "0.9"
tokio-stream = { workspace = true, features = ["sync"] }
